### ISSUE TITLE
the package could not build the vignette

### ISSUE THREAD

**Issue by slphyx** [WSpiller/MVMR#1]
Hi, the package could not be installed. it seems to have the problem in loading the workflow picture in the markdown file MVMR Tutorial.rmd  "C:/Users/ws16063/OneDrive - University of Bristol/Desktop/MVMR/Workflow.png)"

can this workflow picture be shared explicitly in the package? 
Thank you very much for this great package.

**Comment by remlapmot** [comment]
As you probably realise the quick fix for this is to install the package without building the vignette
```r
remotes::install_github("WSpiller/MVMR")
```

**Comment by slphyx** [comment]
Thank you. Yes, I just installed it without building the vignette.

**Comment by remlapmot** [comment]
Great - and in fact you can already see @WSpiller's vignette because since the html vignette is in this repo, you can see it using GitHub & BitBucket HTML Preview [here](https://htmlpreview.github.io/?https://github.com/WSpiller/MVMR/blob/master/vignettes/MVMR%20Tutorial.html).
