### ISSUE TITLE
remotes::install_github("WSpiller/RMVMR",build_opts = c("--no-resave-data","--no-manual"),build_vignettes = TRUE) 错误: Failed to install 'unknown package' from GitHub:   Timeout was reached: [api.github.com] Failed to connect to api.github.com port 443 after 10013 ms: Timeout was reached

### ISSUE THREAD

**Issue by liaofengnan** [WSpiller/MVMR#15]
Hello,when I install RMVMR,it always take mistake like the following:
remotes::install_github("WSpiller/RMVMR",build_opts = c("--no-resave-data","--no-manual"),build_vignettes = TRUE)
错误: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Failed to connect to api.github.com port 443 after 10013 ms: Timeout was reached
Can you help me solve it? Thank you

**Comment by remlapmot** [comment]
You can install both MVMR and RMVMR from our <https://mrcieu.r-universe.dev/> using the following code (on Windows and macOS)

```r
install.packages(c('MVMR', 'RMVMR'), repos = c('https://mrcieu.r-universe.dev', 'https://cloud.r-project.org'))
```

(If you are using Ubuntu [or a Debian based] Linux you need to tweak the code as per [here](https://github.com/MRCIEU/mrcieu.r-universe.dev?tab=readme-ov-file#ubuntu-jammy-jellyfish))

Additionally you can setup a GitHub personal access token (PAT) which will allow you more downloads from GitHub in a set period of time. For instructions, see <https://usethis.r-lib.org/articles/git-credentials.html#get-a-personal-access-token-pat>

**Comment by liaofengnan** [comment]
Thank you for your help! It really works!



At 2024-03-09 22:30:20, "Tom Palmer" ***@***.***> wrote:

You can install both MVMR and RMVMR from our https://mrcieu.r-universe.dev/ using the following code (on Windows and macOS)

install.packages(c('MVMR', 'RMVMR'), repos= c('https://mrcieu.r-universe.dev', 'https://cloud.r-project.org'))

(If you are using Ubuntu [or a Debian based] Linux you need to tweak the code as per here)

Additionally you can setup a GitHub personal access token (PAT) which will allow you more downloads from GitHub in a set period of time. For instructions, see https://usethis.r-lib.org/articles/git-credentials.html#get-a-personal-access-token-pat

**Comment by remlapmot** [comment]
Closing as answer provided.
