### ISSUE TITLE
Vignette input problem

### ISSUE THREAD

**Issue by JonnyBaseball** [WSpiller/MVMR#2]
> vignette("MVMR Tutorial")
Warning message:
vignette ‘MVMR Tutorial’ not found 
> vignette(package="MVMR Tutorial")
Error in find.package(package, lib.loc) : 
  there is no package called ‘MVMR Tutorial’

I have installed MVMR but I am unable to find the MVMR Tutorial.  Thanks!

**Comment by remlapmot** [comment]
@WSpiller  has renamed the vignette to simply *MVMR*. So if you built the vignette when you installed the package then the following should work:
``` r
vignette("MVMR")
```

Or you can view it through the GitHub/BitBucket preview service at
<https://htmlpreview.github.io/?https://github.com/WSpiller/MVMR/blob/master/vignettes/MVMR.html>

But the `README` does need the little update.

**Comment by JonnyBaseball** [comment]
Awesome.  Thank you for the clarification!

V/R
Dan
