### ISSUE TITLE
Sign of beta in causal effect estimation

### ISSUE THREAD

**Issue by MaVdb** [WSpiller/MVMR#4]
I have performed IVW multivariable MR with both MVMR R package and TwoSampleMR R package. 

For analysis 1 with exposures X1, X2 and outcome Y: causal effect estimates are exactly the same and in the same direction as TwoSampleMR R package

For analysis 2 with exposures X2, X3 and outcome Y:  Causal effect estimates are the same, but in the opposite direction. 
Therefore I was wondering how the beta's are harmonized.

Is the causal estimate for exposure1, conditioned upon exposure2 always for an increase (or decrease) for exposure?

Thank you in advance!

**Comment by remlapmot** [comment]
Please could you post a reproducible code example where this happens.

**Comment by MaVdb** [comment]
It was an error from my side, with a mistake in data harmonisation of outcome dataset. 
The problem is solved now.  Apologies for this

**Comment by remlapmot** [comment]
that's fine - no probs
